### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by naive-ikun** [SunnyHaze/miSRGAN-pytorch#1]
Hello, may I ask what environment is required for this code to run？Is it convenient to teach me? Thank you

**Comment by SunnyHaze** [comment]
Thank you for your attention! You should at least make sure that you have at least a computer (server) with an NVIDIA GPU. Otherwise, it may take a long time to train. You should install Python and  PyTorch first, then use `pip install -r requirements.txt` command to install all dependencies that need to run our code.

Note that the `torchrun` command if for distributed(multi-GPU) training. If you only have one GPU, you could slightly modify the start command with various tutorials on the Internet to fit your requirements.

For example, our code is running on a Ubuntu 20.04 LTS server with  NVIDIA TITAN Xp. The software version is: Pytorch 1.10.1 + CUDA 11.3. All versions after this should work.

Hope this solve your problem, feel free to reach out if you have further question, dear ikun.

**Comment by naive-ikun** [comment]
Hello teacher! I will venture to interrupt you, I am a graduate student in the direction of image processing, currently doing research in the direction of image processing based on deep learning, I am fortunate to see the paper and code you wrote, can I bother to ask you for a preprocessed data set. Thank you and look forward to your reply. Have a good life.
| |
高晓坤
|
|
***@***.***
|
---- Replied Message ----
| From | Ma Xiaochen ***@***.***> |
| Date | 8/18/2023 01:45 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [SunnyHaze/miSRGAN-pytorch] hello (Issue #1) |

Thank you for your attention! You should at least make sure that you have at least a computer (server) with an NVIDIA GPU. Otherwise, it may take a long time to train. You should install Python and PyTorch first, then use pip install -r requirements.txt command to install all dependencies that need to run our code.

Note that the torchrun command if for distributed(multi-GPU) training. If you only have one GPU, you could slightly modify the start command with various tutorials on the Internet to fit your requirements.

For example, our code is running on a Ubuntu 20.04 LTS server with NVIDIA TITAN Xp. The software version is: Pytorch 1.10.1 + CUDA 11.3. All versions after this should work.

Hope this solve your problem, feel free to reach out if you have further question, dear ikun.

**Comment by SunnyHaze** [comment]
Do you have Wechat or QQ? You can send me your account through email privately. Discussing through these platforms would be more convenient. My academic email: xiaochen.ma.cs@gmail.com.
